# Generated by Django 3.1 on 2020-09-03 20:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('unesco', '0003_auto_20200903_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
    ]
