# Generated by Django 3.1 on 2020-09-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0004_auto_20200903_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
