# Generated by Django 3.1 on 2020-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0005_auto_20200903_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
