# Generated by Django 3.1 on 2020-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(db_column='Case', max_length=6)),
                ('amount', models.CharField(db_column='Amount', max_length=11)),
                ('status', models.CharField(db_column='Status', max_length=200)),
                ('postedby', models.CharField(db_column='Posted By', max_length=100)),
                ('postdate', models.CharField(db_column='Post Date', max_length=6)),
                ('so', models.CharField(db_column='SO #', max_length=6)),
                ('date_added', models.CharField(db_column='DateAdded', max_length=30)),
            ],
            options={
                'db_table': 'bond',
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(db_column='SO #', max_length=6)),
                ('error', models.CharField(db_column='error', max_length=6)),
            ],
            options={
                'db_table': 'errors',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(db_column='Sex', max_length=2)),
                ('age', models.CharField(db_column='Age', max_length=3)),
                ('height', models.CharField(db_column='Height', max_length=4)),
                ('weight', models.CharField(db_column='Weight', max_length=4)),
                ('race', models.CharField(db_column='Race', max_length=30)),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('so', models.CharField(db_column='SO #', max_length=6)),
                ('date_added', models.CharField(db_column='DateAdded', max_length=30)),
                ('runtime', models.CharField(db_column='RunTime', max_length=8)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Arrestee Name', max_length=200)),
                ('housing', models.CharField(db_column='Housing', max_length=8)),
                ('so', models.CharField(db_column='SO #', max_length=6)),
                ('booking', models.CharField(db_column='Booking', max_length=6)),
                ('booking_dt', models.CharField(db_column='Booking Date/Time', max_length=6)),
                ('age', models.CharField(db_column='Age', max_length=2)),
                ('sex', models.CharField(db_column='Sex', max_length=2)),
                ('race', models.CharField(db_column='Race', max_length=2)),
                ('ethnicity', models.CharField(db_column='Ethnicity', max_length=20)),
                ('tp', models.CharField(db_column='TP', max_length=2)),
                ('charges', models.CharField(db_column='Charges', max_length=400)),
                ('dt', models.CharField(db_column='dt', max_length=20)),
                ('firstname', models.CharField(db_column='First Name', max_length=100)),
                ('lastname', models.CharField(db_column='Last Name', max_length=30)),
                ('date_added', models.CharField(db_column='Date_Added', max_length=30)),
            ],
            options={
                'db_table': 'roster',
            },
        ),
    ]
