# Generated by Django 3.1 on 2020-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailfund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='bondmax',
            field=models.FloatField(db_column='bondmax', default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='bondmean',
            field=models.FloatField(db_column='bondmean', default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='bondmedian',
            field=models.FloatField(db_column='bondmedian', default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='bondmin',
            field=models.FloatField(db_column='bondmin', default=0, max_length=7),
            preserve_default=False,
        ),
    ]
