# Generated by Django 3.1 on 2020-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('lw', 'Low'), ('md', 'Medium'), ('hg', 'High')], default='lw', max_length=2),
        ),
    ]
