# Generated by Django 3.1 on 2020-09-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ideas', '0003_auto_20200905_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
