# Generated by Django 3.1 on 2020-09-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ideas', '0006_auto_20200905_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='linkedin_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
