# Generated by Django 3.1 on 2020-09-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_ideas', '0007_ideas_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
